<?php

function kavamyaccount_views_pre_render(&$view) {
  if ($view->name == 'myaccount' && $view->current_display == 'block') {
  }
}

function kavamyaccount_views_pre_view(&$view, &$display_id, &$args) {
  if ($view->name == 'myaccount' && $view->current_display == 'block') {
    $helper = new kavamyaccount_helper();

    foreach ($helper->accountFields as $uniqueName => $value) {
      // add the item to the view
      $view->add_item(
        $view->current_display,
        'field',
        'views',
        'nothing',
        [
          'label' => $value[0],
          'type' => 'input',
          'alter' => ['text' => $value[1]],
          'element_class' => $uniqueName,
          'element_default_classes' => 1,
        ],
        $uniqueName
      );
    }

  }
}